; Name: Thuong Nguyen
; Course: CSC 3310
; Assignment: Scheme Game - blackjack
; Date: 11/25/2022

(newline)
(display "Welcome to our humble blackjack game")
(newline)
(display "enter (start) to begin.")
(newline)

(define (start)
    (let ((your-card (+ (ran 10) 1)))
        (display "Let's start with your hand: ")
        (display your-card)
        (newline)
        (game-check (take-card your-card) (opponent-card))
    )
)

(define (ran a)
    (random a)
)

(define (game-check a b)
    (display "They have: ")
    (display b)
    (newline)
    (if (> a 21)
        (display "They win.")
        (if (= a b)
            (display "Its a draw.")
            (if (< a b)
                (display "They win.")
                (display "You win.")
            )
        )
    )
)

(define (take-card a) 

    (let ((b (+ (ran 10) 1)))
        (display "You draw: ")
        (display b)
        (newline)
        (display "Your card value now is: ") 
        (display (+ b a))
        (newline)
        (display "Opponent draw their card.")
        (newline)
        (display "Would you draw more? (press 5 to draw)")
        (let ((user-input (read)))
            (if (equal? user-input 5) 
                (take-card (+ b a))
                (+ b a)
            )
        )
    )
)

(define (opponent-card)
    (+ (ran 7) 15)
)
